export enum PaymentSystemEnum {
  PAYEER = 'PAYEER',
  VOLET = 'VOLET',
  WATA = 'WATA',
  TELEGRAM = 'TELEGRAM',
  CRYPTOMUS = 'CRYPTOMUS',
  CRYPTOBOT = 'CRYPTOBOT',
  TON_BLOCKCHAIN = 'TON_BLOCKCHAIN',
  PAYPALYCH = 'PAYPALYCH',
  SKINSBACK = 'SKINSBACK',
  TOME = 'TOME',
}
