export enum PaymentMethodEnum {
  STARS = 'STARS',
  AURAPAY_CARD = 'AURAPAY_CARD',
  AURAPAY_SBP = 'AURAPAY_SBP',
  PLATEGA_CARD = 'PLATEGA_CARD',
  PLATEGA_SBP = 'PLATEGA_SBP',
  HELEKET = 'HELEKET',
  CRYPTOBOT = 'CRYPTOBOT',
  XROCKET = 'XROCKET',
  TON_TON = 'TON_TON', // GRAM ex-ton
  USDT_TON = 'USDT_TON', // USDT в сети ton
}
