export enum IconTypeEnum {
  APPLE_STORE = 'APPLE_STORE',
  PLAY_MARKET = 'PLAY_MARKET',
  MICROSOFT_STORE = 'MICROSOFT_STORE',
  AMAZON_STORE = 'AMAZON_STORE',
  APP_GALLERY = 'APP_GALLERY',
  RU_STORE = 'RU_STORE',
  OTHER = 'OTHER',
}
